export const en = {
    header: {
        signin: "Sign In",
        signup: "Sign Up",
        signout: "Sign Out",
        categories: "Categories",
        add_category: "Add Category",
        shopping_bag: "Shopping Bag",
        recipes: "Recipes",
        add_recipe: "Add Recipe",
        homepage: "Home Page"
    },
    recipes: {
        name: "Name",
        difficulty: "Difficulty",
        description: "Description",
        category: "Category",
        filter_by: "Filter by",
        select_all_categories: "All categories",
        image: "Image",
        instructions: "Instructions",
        remove: "Remove",
        add_step: "Add Step",
        ingredients: "Ingredients",
        type: "Type",
        ingredient_name: "Ingredient Name",
        ingredient_amount: "Ingredient Amount", // הוסף כאן
        ingredient_quantity: "Quantity and Details",
        recipe_not_found: "Recipe not found :(",
        add_ingredient: "Add Ingredient",
        add_recipe: "New Recipe",
        edit_recipe: "Edit Recipe",
        details: "Details",
        cancel: "Cancel",
        save: "Save",
        complex: "Hard",
        medium: "Medium",
        easy: "Easy",
        print: "Print",
        edit: "Edit",
        delete: "Delete",
        not_found: "No recipes match the filters",
        empty: "Your recipe book is empty! Time to fill it with your delicious creations!",
        add_items_to_cart: "Add all ingredients to shopping cart",
        no_category: "To create a recipe, please add at least one category.",
        must_have_name: "Recipe must have a name"
    },
    categories: {
        add_category: "New Category",
        edit_category: "Edit Category",
        delete_category: "Delete Category",
        add: "Add",
        cancel: "Cancel",
        save: "Save",
        insert_cateogry_name: "Category Name",
        name_required: "Category name is required",
        name_too_short: "Name is too short",
        name_too_long: "Name is too long",
        empty: "No categories yet. Organize your recipes by adding your first category!"
    },
    auth: {
        not_registred: "New here?",
        already_registred: "Already signed up?",
        signup_here: "Click here to sign up",
        signin_here: "Click here to sign in",
        continue: "Continue",
        username: "Username",
        password: "Password",
        email: "Email",
        phone: "Phone Number",
        name: "Name",
        field_required: "Field is required",
        field_invalid: "Invalid field",
        name_too_short: "Name is too short",
        name_too_long: "Name is too long",
        password_should_include_capital: "Password must include at least one uppercase letter",
        password_should_include_lower: "Password must include at least one lowercase letter",
        password_should_include_number: "Password must include at least one digit",
        password_should_not_include_spaces: "Password must not contain spaces",
        password_too_short: "Password must be at least 8 characters",
        password_too_long: "Password can be at most 32 characters",
        email_invalid: "Please enter a valid email address",
        phone_invalid: "Please enter a valid phone number",
        signin_failed: "Incorrect username or password",
        signin_success: "Welcome {{username}}!",
        signup_failed: "Signup failed. Please check your details and try again",
        signup_success: "Welcome {{username}}! You have successfully signed up",
        signout_sucess: "You have been logged out"
    },
    shoppingBag: {
        print: "Print",
        clear_all_cart: "Clear all items",
        empty_cart: "The shopping list is empty"
    },
    homepage: {
        welcome_title: "Welcome to {{brand}} 🍳",
        welcome_text_1: "This isn’t just another recipe site. Metkonia was born from a real need – to store, organize, and access the recipes you actually use.",
        welcome_text_2: "Instead of getting lost between pages, notes, or photos, each recipe gets its own proper, neat, and beautiful home.",
        welcome_text_3: "This is your personal cookbook – always available and easy to use, from any computer, anytime.",
        what_to_expect: "📌 What’s waiting for you here?",
        features: [
            "Create and save your own recipes",
            "Organize by personalized categories",
            "Keep track of ingredients and preparation steps",
            "Add ingredients directly to a shopping list",
            "Clean, simple, and user-friendly design"
        ],
        quick_join_title: "⏱ You're just a moment away",
        quick_join_text: "Signup is quick and easy – and opens a whole new world of organized recipe management. This is your chance to build the recipe book you’ve always dreamed of.",
        signup: "Sign Up",
        signin: "Sign In"
    }
};
