export const he = {
    header: {
        signin: "כניסה",
        signup: "הרשמה",
        signout: "יציאה",
        categories: "קטגוריות",
        add_category: "הוסף קטגוריה",
        shopping_bag: "רשימת קניות",
        recipes: "מתכונים",
        add_recipe: "הוספת מתכון",
        homepage: "דף הבית"
    },
    recipes: {
        name: "שם",
        difficulty: "רמת קושי",
        description: "תאור",
        category: "קטגוריה",
        filter_by: "סינון לפי",
        select_all_categories: "כל הקטגוריות",
        image: "תמונה",
        instructions: "הוראות",
        remove: "מחק",
        add_step: "הוספת שלב",
        ingredients: "רכיבים",
        type: "סוג",
        ingredient_name: "שם מרכיב",
        ingredient_amount: "כמות מרכיב", // חשוב לשמור את השדה הזה
        ingredient_quantity: "כמות ופירוט נוסף",
        recipe_not_found: "המתכון לא נמצא :(",
        add_ingredient: "הוספת רכיב",
        add_recipe: "מתכון חדש",
        edit_recipe: "עריכת מתכון",
        details: "להצגה",
        cancel: "ביטול",
        save: "שמירה",
        complex: "קשה",
        medium: "בינוני",
        easy: "קל",
        print: "הדפסה",
        edit: "עריכה",
        delete: "מחיקה",
        not_found: "לא נמצאו מתכונים שעונים על תנאי הסינון",
        empty: "ספר המתכונים שלכם ריק! הזמן למלא אותו ביצירות טעימות!",
        add_items_to_cart: "הוספת כל הרכיבים לסל הקניות",
        no_category: "כדי ליצור מתכון, יש להוסיף לפחות קטגוריה אחת",
        must_have_name: "חובה למלא שם למתכון",
        servings: "מנות",
        for: "עבור",
        upload_image: "העלאת תמונה",
        change_image: "שינוי תמונה",
        remove_image: "הסרת תמונה"
    },
    categories: {
        add_category: "קטגוריה חדשה",
        edit_category: "עריכת קטגוריה",
        delete_category: "מחיקת קטגוריה",
        add: "הוספה",
        cancel: "ביטול",
        save: "שמירה",
        insert_cateogry_name: "שם קטגוריה",
        name_required: "חובה להזין שם לקטגוריה",
        name_too_short: "השם קצר מידי",
        name_too_long: "השם ארוך מידי",
        empty: "נראה שאין עדיין קטגוריות. הוסיפו קטגוריות וארגנו את ספר המתכונים שלכם!",
        delete_error: "לא ניתן למחוק קטגוריה שמשויכת למתכון כלשהו"
    },
    auth: {
        not_registred: "חדשה באתר?",
        already_registred: "כבר נרשמת?",
        signup_here: "לחצי כאן להרשמה",
        signin_here: "לחצי כאן לכניסה",
        continue: "המשיכי",
        username: "שם משתמש",
        password: "סיסמה",
        email: "כתובת מייל",
        phone: "מס' טלפון",
        name: "שם",
        field_required: "שדה חובה",
        field_invalid: "הערך של השדה אינו חוקי",
        name_too_short: "השם קצר מידי",
        name_too_long: "השם ארוך מידי",
        password_should_include_capital: "הסיסמה חייבת לכלול לפחות אות גדולה אחת",
        password_should_include_lower: "הסיסמה חייבת לכלול לפחות אות קטנה אחת",
        password_should_include_number: "הסיסמה חייבת לכלול לפחות ספרה אחת",
        password_should_not_include_spaces: "הסיסמה לא יכולה לכלול רווחים",
        password_too_short: "הסיסמה חייבת להכיל לפחות 8 תווים",
        password_too_long: "הסיסמה יכולה להכיל עד 32 תווים בלבד",
        email_invalid: "יש להזין כתובת מייל תקינה",
        phone_invalid: "יש להזין מספר טלפון תקין",
        signin_failed: "שם המשתמש או הסיסמה שגויים",
        signin_success: "{{username}}, טוב לראות אותך בחזרה!",
        signup_failed: "ההרשמה נכשלה, נא לוודא את הפרטים ולנסות שוב",
        signup_success: "{{username}}, נרשמת בהצלחה",
        signout_sucess: "התנתקת בהצלחה"
    },
    shoppingBag: {
        print: "הדפסה",
        clear_all_cart: "מחיקת כל המצרכים",
        empty_cart: "רשימת המצרכים ריקה"
    },
    homepage: {
        welcome_title: "ברוכה הבאה ל־{{brand}} 🍳",
        welcome_text_1: "זה לא עוד אתר מתכונים. מתכוניה נולדה מתוך צורך אמיתי – לשמור, לארגן ולהנגיש את המתכונים שאת באמת משתמשת בהם.",
        welcome_text_2: "במקום להיאבד בין דפים, פתקים או צילומים, כל מתכון מקבל מקום של כבוד, מסודר ומעוצב.",
        welcome_text_3: "זוהי המחברת האישית שלך, שתישאר תמיד זמינה ונוחה – מכל מחשב, בכל זמן.",
        what_to_expect: "📌 מה מחכה לך כאן?",
        features: [
            "יצירה ושמירה של מתכונים אישיים",
            "ארגון לפי קטגוריות מותאמות אישית",
            "תיעוד מסודר של מרכיבים ושלבי הכנה",
            "אפשרות להוספת מצרכים ישירות לרשימת קניות",
            "עיצוב פשוט, נקי וידידותי לשימוש"
        ],
        quick_join_title: "⏱ תוך רגע את בפנים",
        quick_join_text: "ההרשמה פשוטה ומהירה, פותחת בפנייך עולם נוח ומדויק לניהול המתכונים שלך. זה הזמן לארגן את ספר המתכונים שתמיד חלמת עליו.",
        signup: "הרשמה",
        signin: "התחברות"
    }
};
